vip_R_v2 <- function(w, r2) {
  #print("IN VIP")
  #k <- nrow(w)
  #a <- ncol(w)
  #print(k)
  #print(a)
  # library(SuperPCA)
  source("/pipeline/workflow/scripts/scNOVA_scripts/script_PLSDA/normc.R")
  #print(normc(w)^2)
  #print(diag(r2))
  test <- (normc(w)^2) %*% diag(r2)
  #write.table(test, "/pipeline/debug/vipTest.txt", sep="\t")
  #print("WRITE IN VIP")
  vip <- sqrt(rowSums((normc(w)^2) %*% diag(r2)) / sum(r2) * nrow(w))
  #print("VIPOUT")
  return(vip)
}
