name: MosaiCatcher advanced modules checks

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  schedule:
    - cron: "0 0 * * 0"

jobs:
  Testing-with-MultiQC:
    runs-on: ubuntu-latest
    # needs:
    #   - Formatting
    #   - Linting
    #   - Testing-basic-v7
    #   - Testing-basic-with-ashleys
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # lfs: true

      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules
          git submodule update --remote --recursive --force --init

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_mosaicatcher.yaml --config MultiQC=True ashleys_pipeline=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-ms-norm:
    runs-on: ubuntu-latest
    # needs:
    #   - Formatting
    #   - Linting
    #   - Testing-basic-v7
    #   - Testing-basic-with-ashleys
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # lfs: true

      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules
          git submodule update --remote --recursive --force --init

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_mosaicatcher.yaml --config multistep_normalisation=True ashleys_pipeline=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-breakpointR-only:
    runs-on: ubuntu-latest
    # needs:
    #   - Formatting
    #   - Linting
    #   - Testing-basic-v7
    #   - Testing-basic-with-ashleys
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # lfs: true

      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules
          git submodule update --remote --recursive --force --init

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_mosaicatcher.yaml --config breakpointR=True breakpointR_only=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile

  Testing-with-whatshap-only:
    runs-on: ubuntu-latest
    # needs:
    #   - Formatting
    #   - Linting
    #   - Testing-basic-v7
    #   - Testing-basic-with-ashleys
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # lfs: true

      - name: Git Submodule Update
        run: |
          # git pull --recurse-submodules
          git submodule update --remote --recursive --force --init

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Add Conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: conda install -c conda-forge mamba

      - name: Setup Snakemake
        run: mamba install -c conda-forge -c bioconda snakemake==7.32.4

      - name: List options of workflow
        run: |
          snakemake --cores 1 --config list_commands=True --verbose --debug

      - name: Run workflow
        run: |
          snakemake --cores 1 --use-conda --configfile .tests/config/simple_config_mosaicatcher.yaml --config whatshap_only=True \
          --conda-frontend mamba -p --verbose --debug --snakefile workflow/Snakefile
